server:
  port: 80
  servlet:
    context-path: /api
    
    
import-xlsx:
  path: classpath:init.xlsx

spring:
  application:
    name: scaffold-demo
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # 关键：允许远程连接
        trace: false            # 生产环境关闭trace
        
  # MyBatis-Plus Configuration
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.scaffold.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      column-underline: false

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-version: true
    enable-author: true